In [2]:
import pandas as pd #for data handling
pd.options.display.max_rows = 999 #set the max no of rows you can see. 
pd.set_option('display.max_columns', 999) #another way to do the same thing

import seaborn as sns #for higher-level  visualisation
import numpy as np #for matrix operation
import matplotlib.pyplot as plt #for lower-level visualisation

# Step 1: Load Data

In [3]:
train_df = pd.read_csv("dataset.csv")

In [4]:
train_df.sample(5)

a_0     a_1     a_2  a_3       a_4       a_5  a_6  a_7  a_8  \
372447     4044   18.17  3.3333    3  0.000000  0.007463    1    2    1   
417339     2636  299.00  4.7468  237  0.007862  0.989443    5    2    1   
85042      4044   89.99  4.8136   59  0.000000  0.189115    3    2    0   
96752   1115193    8.47  4.2334  347  0.005391  0.181926    1    2    0   
184530     4044   55.00  5.0000    3  0.032710  0.080269    4    2    1   

          a_9   a_10   a_11   a_12   a_13   a_14   a_15  a_16  a_17  a_18  \
372447  False  False  False   True  False  False   True     1     1     0   
417339  False  False  False  False  False   True   True     1     1     0   
85042   False  False  False   True  False  False   True     0     4     0   
96752   False   True  False   True  False  False  False     2     6     0   
184530  False  False  False   True  False  False  False     2     8     0   

        a_19  a_20  a_21  a_22      a_23      a_24  a_25  a_26  a_27  a_28  \
372447     0    18     2     0  0.000000  0.000250     1     0     0     0   
417339     0    15     2     0  0.003433  0.003683     0     0     0     0   
85042      0    22     2     0  1.610583  1.610833     0     0     0     0   
96752      0    20     2     3  3.372750  3.373000     0     0     0     0   
184530     0     5     2     5  1.934133  1.934383     0     0     0     0   

        a_29  a_30  a_31  a_32  a_33  a_34  a_35  a_36  a_37  a_38  a_39  \
372447     1     1     0     0     0     1     1     1     0     0     0   
417339     4     0     0     0     0     1     1     1     0     0     0   
85042      4     0     0     0     0     2     9    17     0     0     2   
96752      4     0     0     0     0     1     2     6     0     0     3   
184530     4     0     0     0     0     1     2     8     0     0     5   

             a_40      a_41  a_42  a_43  a_44  a_45  a_46  a_47  a_48  a_49  \
372447   0.000000  0.000250     1     0     0     0     1     1     0     0   
417339   0.003433  0.003683     0     0     0     0     4     0     0     0   
85042   14.310867  7.155683     6     0    97     0     1     6     0    96   
96752    3.372750  3.373000     0     0     0     0     4     0     0     0   
184530   1.934133  1.934383     0     0     0     0     4     0     0     0   

        a_50  a_51  a_52  a_53  a_54  a_55  a_56       a_57       a_58  a_59  \
372447     0     1     1     1     0     0     0   0.000000   0.000250     1   
417339     0     1     1     1     0     0     0   0.003433   0.003683     0   
85042      0     5    20    31     0     0     4  21.501800   4.300610    14   
96752      0     3    24    69    10    15    20  34.388167  11.462972     0   
184530     0     1     2     8     0     0     5   1.934133   1.934383     0   

        a_60  a_61  a_62  a_63  a_64  a_65  a_66  a_67  a_68  a_69  a_70  \
372447     0     0     0     1     1     0     0     0     1     1     1   
417339     0     0     0     4     0     0     0     0     1     1     1   
85042      0   181     0     1    11     0   146     0     5    20    31   
96752      0     0     0     4     0     0     0     0     5    33    81   
184530     0     0     0     4     0     0     0     0     3     5    23   

        a_71  a_72  a_73       a_74      a_75  a_76  a_77  a_78  a_79  a_80  \
372447     0     0     0   0.000000  0.000250     1     0     0     0     1   
417339     0     0     0   0.003433  0.003683     0     0     0     0     4   
85042      0     0     4  21.501800  4.300610    14     0   181     0     1   
96752     12    16    20  49.589083  9.918067     1     0     0     0     4   
184530     0     0    14  14.307583  4.769444     0     0     0     0     4   

        a_81  a_82  a_83  a_84   a_85 a_86 a_87  label  
372447     1     0     0     0  False   ad   sm      0  
417339     0     0     0     0  False   ie   or      0  
85042     11     0   146     0  False   ad   oc      0  
96752      1     0     0     0  False   ws   oc      0  

# Step 2: EDA

## 2.1. Dtypes Check and Fix

In [5]:
train_df.dtypes.unique() #different types of features we have

array([dtype('int64'), dtype('float64'), dtype('bool'), dtype('O')],
      dtype=object)

### 2.1.1. Fix boolean datatype

In [6]:
bool_df = train_df.select_dtypes(include="bool") #take out bool seperately

In [7]:
bool_df.columns #check all the boolean columns

Index(['a_9', 'a_10', 'a_11', 'a_12', 'a_13', 'a_14', 'a_15', 'a_85'], dtype='object')

In [8]:
for column in bool_df.columns:
    print(column)
    del train_df[column]
    train_df[column] = np.where(bool_df[column] == False,0,1)

a_9
a_10
a_11
a_12
a_13
a_14
a_15
a_85


In [9]:
train_df['a_9'].unique()

array([0, 1])

#### Let's check the remaining data types to be converted

In [10]:
train_df.dtypes.unique()

array([dtype('int64'), dtype('float64'), dtype('O')], dtype=object)

### 2.1.2. Fix "object" datatype

In [11]:
object_df = train_df.select_dtypes(include="object") #take out object seperately

In [12]:
object_df.columns #check all object columns

Index(['a_86', 'a_87'], dtype='object')

In [13]:
train_df["a_86"].unique()

array(['ws', 'ie', 'mc', 'tt', 'ad', 'id', 'or'], dtype=object)

In [14]:
train_df["a_86"].value_counts()

ws    156543
ie    142909
ad    120996
mc     28944
id     25414
or     14151
tt     11043
Name: a_86, dtype: int64

In [15]:
train_df["a_87"].unique()

array(['sm', 'oc', 'ae', 'dy', 'el', 'or'], dtype=object)

In [16]:
train_df["a_87"].value_counts()

oc    279315
sm    169816
dy     25896
ae     14792
el      5094
or      5087
Name: a_87, dtype: int64

In [17]:
for column in object_df.columns:
    print(column)
    dummy = pd.get_dummies(train_df[column], prefix = column, drop_first = True)
    train_df = pd.concat([train_df, dummy], axis = 1)
    train_df.drop(column, 1, inplace = True)

a_86
a_87


In [18]:
train_df.sample(5)

a_0    a_1     a_2  a_3       a_4       a_5  a_6  a_7  a_8  a_16  \
312603     5438  18.74  0.0000    0  0.000000  0.008464    3    2    0    98   
66900   1072864  12.81  0.0000    0  0.000000  0.018111    2    2    0     1   
431785       -1   6.94  0.0000    0  0.002332  0.659538    1    2    0     1   
185082     5438  13.79  4.8095   21  0.000000  0.570714    2    2    0     1   
200644       -1   0.00  5.0000    1  0.000000  0.078631    1    1    0     2   

        a_17  a_18  a_19  a_20  a_21  a_22        a_23        a_24  a_25  \
312603    99     0     0     0     2     1  136.491250  136.491500     0   
66900      1     0     0    19     2     0    0.000000    0.000250     1   
431785     1     0     0    10     2     0    0.000000    0.000250     0   
185082     5     0     0    23     2     3    1.041867    1.042117     0   
200644     6     0     0     8     2     0    4.510083    4.510333     0   

        a_26  a_27  a_28  a_29  a_30  a_31  a_32  a_33  a_34  a_35  a_36  \
312603     0     0     0     4     0     0     0     0     2   173   179   
66900      0     0     0     1     1     0     0     0     1     1     1   
431785     0     0     0     4     0     0     0     0     1     1     1   
185082     0     0     0     4     0     0     0     0     2    18    75   
200644     0     0     0     4     0     0     0     0     2     3    10   

        a_37  a_38  a_39        a_40        a_41  a_42  a_43  a_44  a_45  \
312603     0     0     6  253.549167  126.774833     3     0     0     0   
66900      0     0     0    0.000000    0.000250     1     0     0     0   
431785     0     0     0    0.000000    0.000250     0     0     0     0   
185082     4     9    29   30.798283   15.399392     1     0     0     0   
200644     0     0     0   15.090883    7.545692     0     0     0     0   

        a_46  a_47  a_48  a_49  a_50  a_51  a_52  a_53  a_54  a_55  a_56  \
312603     4     1     0     0     0     2   173   179     0     0     6   
66900      1     1     0     0     0     1     1     1     0     0     0   
431785     4     0     0     0     0     1     1     1     0     0     0   
185082     4     1     0     0     0     2    18    75     4     9    29   
200644     4     0     0     0     0     3     3    11     0     0     1   

              a_57        a_58  a_59  a_60  a_61  a_62  a_63  a_64  a_65  \
312603  253.549167  126.774833     3     0     0     0     4     1     0   
66900     0.000000    0.000250     1     0     0     0     1     1     0   
431785    0.000000    0.000250     0     0     0     0     4     0     0   
185082   30.798283   15.399392     1     0     0     0     4     1     0   
200644   15.090883    5.030544     0     0     0     0     4     0     0   

        a_66  a_67  a_68  a_69  a_70  a_71  a_72  a_73        a_74  \
312603     0     0     2   173   179     0     0     6  253.549167   
66900      0     0     1     1     1     0     0     0    0.000000   
431785     0     0     1     1     1     0     0     0    0.000000   
185082     0     0     2    18    75     4     9    29   30.798283   
200644     0     0     8    53   162    13    11    13   87.448833   

              a_75  a_76  a_77  a_78  a_79  a_80  a_81  a_82  a_83  a_84  \
312603  126.774833     3     0     0     0     4     1     0     0     0   
66900     0.000250     1     0     0     0     1     1     0     0     0   
431785    0.000250     0     0     0     0     4     0     0     0     0   
185082   15.399392     1     0     0     0     4     1     0     0     0   
200644   10.931354     0     0     0     0     4     0     0     0     0   

        label  a_9  a_10  a_11  a_12  a_13  a_14  a_15  a_85  a_86_id  \
312603      0    0     0     0     0     1     0     0     0        0   
66900       0    0     1     0     0     0     1     0     0        0   
431785      0    0     0     0     0     0     1     0     0        0   
185082      0    0     1     0     0     0     1     1     0        0   
200

In [19]:
train_df['label'].value_counts()

0    498275
1      1725
Name: label, dtype: int64

## 2.2. Missing Value

In [20]:
train_df.isnull().sum().sum()

0

# Step 3: Defining train test split  (Ran till this point)

In [21]:
features = list(train_df.columns)
features.remove("label")

In [22]:
X = train_df[features].values
X.shape

(500000, 97)

In [23]:
y = train_df["label"].values
y.shape

(500000,)

In [80]:
from sklearn.model_selection import train_test_split

In [111]:
X_train, X_test, Y_train, Y_test = train_test_split (X, y, test_size = 0.20, random_state=42)

In [112]:
np.unique(Y_train,return_counts=True)

(array([0, 1]), array([398592,   1408]))

In [113]:
np.unique(Y_test,return_counts=True)

(array([0, 1]), array([99683,   317]))

# Step 4: PCA for dimensionality reduction

In [114]:
from sklearn.preprocessing import StandardScaler
std = StandardScaler().fit(X_train)
X_train = std.transform(X_train)
X_train.shape

(400000, 97)

ideally the normalised data should have mean of zero and a standard deviation of one

In [115]:
np.mean(X_train), np.std(X_train)

(5.535334115468208e-15, 0.9896370260349382)

In [116]:
from sklearn.decomposition import PCA

In [186]:
pca = PCA(0.99)
X_train_pca = pca.fit_transform(X_train)
X_train_pca.shape

(400000, 56)

# Step 5: Handling class imbalance

In [184]:
np.unique(Y_train,return_counts=True)

(array([0, 1]), array([398592,   1408]))

In [185]:
np.unique(Y_test,return_counts=True)

(array([0, 1]), array([99683,   317]))

## As the data is imbalanced, we will use smote for handling imbalance

In [137]:
from imblearn.over_sampling import SMOTE
X_train_balanced, Y_train_balanced = SMOTE(sampling_strategy=0.1,
                                k_neighbors=3).fit_resample(X_train_pca, Y_train)

In [138]:
X_train_balanced.shape, Y_train_balanced.shape

((438451, 56), (438451,))

In [139]:
np.unique(Y_train_balanced,return_counts=True)

(array([0, 1]), array([398592,  39859]))

# Step 6 : Pipeline for test data conversion

In [187]:
X_test_scaled = std.transform(X_test)

In [189]:
X_test_pca = pca.transform(X_test)
X_test_pca.shape

(100000, 56)

# Step 7 : Modelling

In [44]:
from sklearn.metrics import confusion_matrix, roc_curve, auc
from sklearn.metrics import classification_report
from sklearn.metrics import recall_score
from sklearn.linear_model import LogisticRegression
import xgboost as xgb

In [144]:

# creating the model
model = LogisticRegression(solver="sag", max_iter=500)

# feeding the training data into the model
model.fit(X_train_balanced, Y_train_balanced)

# predicting the test set results
Y_pred = model.predict_proba(X_test_pca)


/Users/keshav.somani/.py_venv/lib/python3.6/site-packages/sklearn/linear_model/sag.py:337: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)


In [169]:
model.classes_, Y_pred

(array([0, 1]), array([[0., 1.],
        [0., 1.],
        [0., 1.],
        ...,
        [0., 1.],
        [0., 1.],
        [0., 1.]]))

In [178]:
y_pred_threshold = (Y_pred[:,1] >= 0.5).astype(bool)

In [179]:
print("Training accuracy :", model.score(X_train_balanced, Y_train_balanced))
print("Testing accuracy :", model.score(X_test_pca, Y_test))

# classification report
print(classification_report(Y_test, y_pred_threshold))

# confusion matrix 
print(confusion_matrix(Y_test, y_pred_threshold))

Training accuracy : 0.9116047175168948
Testing accuracy : 0.07889
              precision    recall  f1-score   support

           0       1.00      0.08      0.14     99683
           1       0.00      0.96      0.01       317

    accuracy                           0.08    100000
   macro avg       0.50      0.52      0.07    100000
weighted avg       1.00      0.08      0.14    100000

[[ 7586 92097]
 [   14   303]]


In [ ]:

# Calculating the accuracies
print("Training accuracy :", model.score(X_train_balanced, Y_train_balanced))
print("Testing accuracy :", model.score(X_test_pca, Y_test))

# classification report
print(classification_report(Y_test, Y_pred))

# confusion matrix 
print(confusion_matrix(Y_test, Y_pred))

In [143]:

eval_set = [(X_test_pca, Y_test)]

model_xgbs = xgb.XGBClassifier(gamma=0.024, learning_rate=0.3, 
                          max_depth=6,
                          nthread=4,
                          n_estimators=1000)

model_xgbs.silent=False

model_xgbs.fit(X_train_balanced, Y_train_balanced, early_stopping_rounds=10, 
          eval_set=eval_set,
          verbose=True) #https://xgboost.readthedocs.io/en/latest/parameter.html

# predicting the test set results
Y_pred = model_xgbs.predict(X_test_pca)

# Calculating the accuracies
print("Training accuracy :", model_xgbs.score(X_train_balanced, Y_train_balanced))
print("Testing accuracy :", model_xgbs.score(X_test_pca, Y_test))

# classification report
print(classification_report(Y_test, Y_pred))

# confusion matrix 
print(confusion_matrix(Y_test, Y_pred))

[0]	validation_0-error:0.02638
Will train until validation_0-error hasn't improved in 10 rounds.
[1]	validation_0-error:0.01575
[2]	validation_0-error:0.01402
[3]	validation_0-error:0.00925
[4]	validation_0-error:0.00774
[5]	validation_0-error:0.00532
[6]	validation_0-error:0.00376
[7]	validation_0-error:0.00391
[8]	validation_0-error:0.00362
[9]	validation_0-error:0.00359
[10]	validation_0-error:0.00536
[11]	validation_0-error:0.00475
[12]	validation_0-error:0.02705
[13]	validation_0-error:0.02763
[14]	validation_0-error:0.07888
[15]	validation_0-error:0.07714
[16]	validation_0-error:0.83772
[17]	validation_0-error:0.79963
[18]	validation_0-error:0.78122
[19]	validation_0-error:0.7461
Stopping. Best iteration:
[9]	validation_0-error:0.00359

Training accuracy : 0.9185359367409357
Testing accuracy : 0.99641
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     99683
           1       0.00      0.00      0.00       317

    accuracy     

In [183]:
train_df.shape[0]

500000

## Feature selection

In [24]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500000 entries, 0 to 499999
Data columns (total 98 columns):
a_0        500000 non-null int64
a_1        500000 non-null float64
a_2        500000 non-null float64
a_3        500000 non-null int64
a_4        500000 non-null float64
a_5        500000 non-null float64
a_6        500000 non-null int64
a_7        500000 non-null int64
a_8        500000 non-null int64
a_16       500000 non-null int64
a_17       500000 non-null int64
a_18       500000 non-null int64
a_19       500000 non-null int64
a_20       500000 non-null int64
a_21       500000 non-null int64
a_22       500000 non-null int64
a_23       500000 non-null float64
a_24       500000 non-null float64
a_25       500000 non-null int64
a_26       500000 non-null int64
a_27       500000 non-null int64
a_28       500000 non-null int64
a_29       500000 non-null int64
a_30       500000 non-null int64
a_31       500000 non-null int64
a_32       500000 non-null int64
a_33       500000 n

In [25]:
from itertools import chain

correlation_threshold = 0.9 # can be switched. Default value 0.99

train_integer = train_df.drop('label',axis=1)

cor = train_integer.corr()
cor.loc[:,:] =  np.tril(cor, k=-1)
cor = cor.stack()
correlated = cor[cor > correlation_threshold].reset_index().loc[:,['level_0','level_1']]
correlated = correlated.query('level_0 not in level_1')
correlated_array =  correlated.groupby('level_0').agg(lambda x: set(chain(x.level_0,x.level_1))).values
correlated_array

array([[{'a_23', 'a_24'}],
       [{'a_27', 'a_32'}],
       [{'a_44', 'a_49'}],
       [{'a_50', 'a_45'}],
       [{'a_36', 'a_53', 'a_35', 'a_52'}],
       [{'a_66', 'a_61'}],
       [{'a_67', 'a_62'}],
       [{'a_70', 'a_69'}],
       [{'a_38', 'a_55', 'a_54', 'a_37', 'a_19', 'a_71', 'a_18'}],
       [{'a_73', 'a_56'}],
       [{'a_58', 'a_75'}],
       [{'a_81', 'a_64', 'a_76'}],
       [{'a_82', 'a_26', 'a_77', 'a_48', 'a_60', 'a_31', 'a_65', 'a_43'}],
       [{'a_78', 'a_83'}]], dtype=object)

In [27]:
correlated_features = []
for sets in correlated_array:
    element_list = list(sets[0])
    for idx, el in enumerate(element_list):
        if idx is not 0:
            correlated_features.append(el)
correlated_features.sort(key = lambda x: int(x[2:]) )
print (correlated_features)

['a_18', 'a_19', 'a_24', 'a_26', 'a_31', 'a_32', 'a_35', 'a_37', 'a_43', 'a_45', 'a_48', 'a_49', 'a_52', 'a_53', 'a_54', 'a_55', 'a_56', 'a_60', 'a_61', 'a_62', 'a_64', 'a_65', 'a_69', 'a_71', 'a_75', 'a_76', 'a_77', 'a_83']


In [28]:
non_cor_train_df = train_df.drop(correlated_features, axis=1 )
non_cor_train_df.shape

(500000, 70)

In [29]:
features_non_cor = list(non_cor_train_df.columns)
features_non_cor.remove("label")

In [30]:
X_non_cor = non_cor_train_df[features_non_cor].values
X_non_cor.shape

(500000, 69)

In [31]:
Y_non_cor = non_cor_train_df["label"].values
Y_non_cor.shape

(500000,)

In [32]:
from sklearn.model_selection import train_test_split

X_non_cor_train, X_non_cor_test, Y_non_cor_train, Y_non_cor_test = \
train_test_split (X_non_cor, Y_non_cor, test_size = 0.20, random_state=42)

In [33]:
np.unique(Y_non_cor_train,return_counts=True)

(array([0, 1]), array([398592,   1408]))

In [34]:
np.unique(Y_non_cor_test,return_counts=True)

(array([0, 1]), array([99683,   317]))

## Now, we will try oversampling of minority class, undersampling of majority class for handling data imbalance

In [35]:
from sklearn.utils import resample

In [36]:
X_non_cor_train.shape, Y_non_cor_train.shape

((400000, 69), (400000,))

In [37]:
# concatenate our training data back together
X_non_cor_full = pd.concat([pd.DataFrame(X_non_cor_train, columns=non_cor_train_df.columns.drop('label')), 
                            pd.DataFrame(Y_non_cor_train, columns=['label'])], axis=1)

In [38]:
X_non_cor_full.sample(5)

a_0     a_1     a_2    a_3       a_4       a_5  a_6  a_7  a_8  \
327816  4044.0   12.99  0.0000    0.0  0.000000  0.013924  1.0  2.0  0.0   
150140  4044.0    9.45  0.0000    0.0  0.000000  0.000455  2.0  2.0  0.0   
245814  4044.0  179.00  4.1598  170.0  0.012872  0.999090  5.0  2.0  0.0   
182323  4044.0    3.99  0.0000    0.0  0.000000  0.000273  1.0  2.0  0.0   
153624  4125.0   17.00  5.0000    2.0  0.010554  0.065799  2.0  2.0  0.0   

        a_16  a_17  a_20  a_21  a_22       a_23  a_25  a_27  a_28  a_29  a_30  \
327816   1.0   1.0  14.0   2.0   0.0   0.000000   1.0   0.0   0.0   1.0   1.0   
150140   9.0  15.0  18.0   2.0   4.0  26.123033   9.0  82.0   0.0   1.0   5.0   
245814   0.0   2.0  11.0   2.0   2.0   1.849317   0.0   0.0   0.0   4.0   0.0   
182323   5.0  23.0  14.0   2.0  16.0  66.240783   1.0  11.0   0.0   3.0   1.0   
153624   6.0   8.0   8.0   2.0   0.0   7.399900   5.0   0.0   0.0   1.0   5.0   

        a_33  a_34  a_36  a_38  a_39       a_40       a_41  a_42  a_44  a_46  \
327816   0.0   3.0   4.0   0.0   2.0   0.149433   0.050061   2.0  32.0   1.0   
150140   0.0   2.0  17.0   0.0   4.0  38.441350  19.220925  11.0  82.0   1.0   
245814   0.0   2.0   6.0   0.0   5.0   2.488150   1.244325   0.0   0.0   4.0   
182323   0.0   2.0  24.0   0.0  16.0  66.240783  33.120642   1.0  11.0   3.0   
153624   0.0   2.0   9.0   0.0   0.0   7.399900   3.700200   5.0   0.0   1.0   

        a_47  a_50  a_51       a_57       a_58  a_59  a_63  a_66  a_67  a_68  \
327816   1.0   0.0   5.0   2.114467   0.423143   4.0   1.0  18.0   0.0   8.0   
150140   5.0   0.0   2.0  38.441350  19.220925  11.0   1.0  40.0   0.0   6.0   
245814   0.0   0.0   3.0   3.001150   1.000633   0.0   4.0   0.0   0.0   4.0   
182323   1.0   0.0   2.0  66.240783  33.120642   1.0   3.0   2.0   0.0   2.0   
153624   5.0   0.0   2.0   7.399900   3.700200   5.0   1.0   0.0   0.0   2.0   

        a_70  a_72  a_73       a_74    a_78  a_79  a_80  a_81  a_82  a_84  \
327816  87.0   4.0  37.0  76.146117  1282.0   1.0   1.0  16.0   1.0   1.0   
150140  33.0   3.0   5.0  46.325933    82.0   0.0   1.0   5.0   0.0   0.0   
245814  12.0   0.0   8.0   4.603633     0.0   0.0   4.0   0.0   0.0   0.0   
182323  24.0   0.0  16.0  66.240783    11.0   0.0   3.0   1.0   0.0   0.0   
153624   9.0   0.0   0.0   7.399900     0.0   0.0   1.0   5.0   0.0   0.0   

        a_9  a_10  a_11  a_12  a_13  a_14  a_15  a_85  a_86_id  a_86_ie  \
327816  0.0   0.0   0.0   0.0   0.0   1.0   1.0   1.0      0.0      0.0   
150140  0.0   1.0   0.0   0.0   0.0   1.0   1.0   0.0      0.0      1.0   
245814  0.0   0.0   0.0   0.0   0.0   1.0   1.0   0.0      0.0      1.0   
182323  0.0   0.0   0.0   0.0   0.0   1.0   0.0   0.0      0.0      0.0   
153624  0.0   0.0   0.0   0.0   0.0   1.0   1.0   0.0      0.0      0.0   

        a_86_mc  a_86_or  a_86_tt  a_86_ws  a_87_dy  a_87_el  a_87_oc  \
327816      0.0      0.0      0.0      0.0      0.0      0.0      1.0   
150140      0.0      0.0      0.0      0.0      0.0      0.0      1.0   
245814      0.0      0.0      0.0      0.0      0.0      0.0      1.0   
182323      0.0      1.0      0.0      0.0      0.0      0.0      1.0   
153624      0.0      0.0      0.0      0.0      0.0      0.0      1.0   

        a_87_or  a_87_sm  label  
327816      0.0      0.0      0  
150140      0.0      0.0      0  
245814      0.0      0.0      0  
182323      0.0      0.0      0  
153624      0.0      0.0      0

In [39]:
class_majority = X_non_cor_full[X_non_cor_full['label']==0]
class_minority = X_non_cor_full[X_non_cor_full['label']==1]

In [40]:
minority_upsampled = resample(class_minority,
                          replace=True, # sample with replacement
                          n_samples=len(class_majority), # match number in majority class
                          random_state=27) # reproducible results

# combine majority and upsampled minority
upsampled = pd.concat([class_majority, minority_upsampled])

In [41]:
upsampled.label.value_counts()

1    398592
0    398592
Name: label, dtype: int64

In [42]:
Y_train_upsampled = upsampled.label
X_train_upsampled = upsampled.drop('label', axis=1)

In [53]:
print(X_train_upsampled.shape, Y_train_upsampled.shape, X_train_upsampled.columns)

(797184, 69) (797184,) Index(['a_0', 'a_1', 'a_2', 'a_3', 'a_4', 'a_5', 'a_6', 'a_7', 'a_8', 'a_16',
       'a_17', 'a_20', 'a_21', 'a_22', 'a_23', 'a_25', 'a_27', 'a_28', 'a_29',
       'a_30', 'a_33', 'a_34', 'a_36', 'a_38', 'a_39', 'a_40', 'a_41', 'a_42',
       'a_44', 'a_46', 'a_47', 'a_50', 'a_51', 'a_57', 'a_58', 'a_59', 'a_63',
       'a_66', 'a_67', 'a_68', 'a_70', 'a_72', 'a_73', 'a_74', 'a_78', 'a_79',
       'a_80', 'a_81', 'a_82', 'a_84', 'a_9', 'a_10', 'a_11', 'a_12', 'a_13',
       'a_14', 'a_15', 'a_85', 'a_86_id', 'a_86_ie', 'a_86_mc', 'a_86_or',
       'a_86_tt', 'a_86_ws', 'a_87_dy', 'a_87_el', 'a_87_oc', 'a_87_or',
       'a_87_sm'],
      dtype='object')


In [54]:
X_non_cor_test.shape, Y_non_cor_test.shape, X_non_cor_test.columns

AttributeError: 'numpy.ndarray' object has no attribute 'columns'

In [45]:
upsampled = LogisticRegression(solver='liblinear').fit(X_train_upsampled, Y_train_upsampled)
upsampled_pred = upsampled.predict(X_non_cor_test)

In [48]:
from sklearn.metrics import accuracy_score, recall_score, precision_score, f1_score

In [46]:
print(accuracy_score(Y_non_cor_test, upsampled_pred), recall_score(Y_non_cor_test, upsampled_pred),
precision_score(Y_non_cor_test, upsampled_pred), f1_score(Y_non_cor_test, upsampled_pred))

0.58104 0.6876971608832808 0.005188623110793764 0.010299536993291128


In [47]:
confusion_matrix(Y_non_cor_test, upsampled_pred)

array([[57886, 41797],
       [   99,   218]])

In [62]:
X_non_cor_test[0]

array([4.04400000e+03, 7.49600000e+01, 4.07140000e+00, 1.40000000e+01,
       0.00000000e+00, 7.16235894e-02, 4.00000000e+00, 2.00000000e+00,
       1.00000000e+00, 1.00000000e+00, 1.00000000e+00, 0.00000000e+00,
       2.00000000e+00, 0.00000000e+00, 6.61833333e-02, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 4.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 1.00000000e+00, 1.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 6.61833333e-02, 6.64333333e-02, 0.00000000e+00,
       0.00000000e+00, 4.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       1.00000000e+00, 6.61833333e-02, 6.64333333e-02, 0.00000000e+00,
       4.00000000e+00, 0.00000000e+00, 0.00000000e+00, 5.00000000e+00,
       1.70000000e+01, 0.00000000e+00, 9.00000000e+00, 2.06467000e+01,
       2.00000000e+00, 0.00000000e+00, 3.00000000e+00, 1.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 1.00000000e+00,
      

In [65]:
X_non_cor_test_1 = pd.DataFrame(X_non_cor_test, columns=non_cor_train_df.columns.drop('label')) 
Y_non_cor_test_1 = pd.DataFrame(Y_non_cor_test, columns=['label'])

In [66]:
eval_set = [(X_non_cor_test_1, Y_non_cor_test_1)]

model_xgbs = xgb.XGBClassifier(gamma=0.024, learning_rate=0.3, 
                          max_depth=6,
                          nthread=4,
                          n_estimators=1000)

model_xgbs.silent=False

model_xgbs.fit(X_train_upsampled, Y_train_upsampled, early_stopping_rounds=10, 
          eval_set=eval_set,
          verbose=True) #https://xgboost.readthedocs.io/en/latest/parameter.html

# predicting the test set results
Y_pred = model_xgbs.predict(X_non_cor_test_1)

# Calculating the accuracies
print("Training accuracy :", model_xgbs.score(X_train_upsampled, Y_train_upsampled))
print("Testing accuracy :", model_xgbs.score(X_non_cor_test_1, Y_non_cor_test_1))

# classification report
print(classification_report(Y_non_cor_test_1, Y_pred))

# confusion matrix 
print(confusion_matrix(Y_non_cor_test_1, Y_pred))
print(precision_score(Y_non_cor_test_1, Y_pred))
print(recall_score(Y_non_cor_test_1, Y_pred))
print(accuracy_score(Y_non_cor_test_1, Y_pred))
print(f1_score(Y_non_cor_test_1, Y_pred))

/Users/keshav.somani/.py_venv/lib/python3.6/site-packages/sklearn/preprocessing/label.py:252: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[0]	validation_0-error:0.22613
Will train until validation_0-error hasn't improved in 10 rounds.
[1]	validation_0-error:0.17699
[2]	validation_0-error:0.17638
[3]	validation_0-error:0.17103
[4]	validation_0-error:0.15839
[5]	validation_0-error:0.15626
[6]	validation_0-error:0.14961
[7]	validation_0-error:0.14594
[8]	validation_0-error:0.1423
[9]	validation_0-error:0.14054
[10]	validation_0-error:0.13872
[11]	validation_0-error:0.13523
[12]	validation_0-error:0.13423
[13]	validation_0-error:0.13081
[14]	validation_0-error:0.1283
[15]	validation_0-error:0.12455
[16]	validation_0-error:0.12237
[17]	validation_0-error:0.11899
[18]	validation_0-error:0.11789
[19]	validation_0-error:0.11618
[20]	validation_0-error:0.11411
[21]	validation_0-error:0.11185
[22]	validation_0-error:0.10915
[23]	validation_0-error:0.10644
[24]	validation_0-error:0.10567
[25]	validation_0-error:0.10411
[26]	validation_0-error:0.10375
[27]	validation_0-error:0.10329
[28]	validation_0-error:0.10074
[29]	validation_0-

[251]	validation_0-error:0.00971
[252]	validation_0-error:0.00971
[253]	validation_0-error:0.00969
[254]	validation_0-error:0.0096
[255]	validation_0-error:0.00954
[256]	validation_0-error:0.00942
[257]	validation_0-error:0.00927
[258]	validation_0-error:0.00925
[259]	validation_0-error:0.00924
[260]	validation_0-error:0.00917
[261]	validation_0-error:0.00908
[262]	validation_0-error:0.00899
[263]	validation_0-error:0.00885
[264]	validation_0-error:0.00891
[265]	validation_0-error:0.00882
[266]	validation_0-error:0.00877
[267]	validation_0-error:0.00871
[268]	validation_0-error:0.0087
[269]	validation_0-error:0.00865
[270]	validation_0-error:0.00858
[271]	validation_0-error:0.00844
[272]	validation_0-error:0.00839
[273]	validation_0-error:0.00826
[274]	validation_0-error:0.0082
[275]	validation_0-error:0.00814
[276]	validation_0-error:0.0081
[277]	validation_0-error:0.00809
[278]	validation_0-error:0.00806
[279]	validation_0-error:0.00803
[280]	validation_0-error:0.00799
[281]	validati

Stopping. Best iteration:
[490]	validation_0-error:0.00397



ValueError: feature_names mismatch: ['a_0', 'a_1', 'a_2', 'a_3', 'a_4', 'a_5', 'a_6', 'a_7', 'a_8', 'a_16', 'a_17', 'a_20', 'a_21', 'a_22', 'a_23', 'a_25', 'a_27', 'a_28', 'a_29', 'a_30', 'a_33', 'a_34', 'a_36', 'a_38', 'a_39', 'a_40', 'a_41', 'a_42', 'a_44', 'a_46', 'a_47', 'a_50', 'a_51', 'a_57', 'a_58', 'a_59', 'a_63', 'a_66', 'a_67', 'a_68', 'a_70', 'a_72', 'a_73', 'a_74', 'a_78', 'a_79', 'a_80', 'a_81', 'a_82', 'a_84', 'a_9', 'a_10', 'a_11', 'a_12', 'a_13', 'a_14', 'a_15', 'a_85', 'a_86_id', 'a_86_ie', 'a_86_mc', 'a_86_or', 'a_86_tt', 'a_86_ws', 'a_87_dy', 'a_87_el', 'a_87_oc', 'a_87_or', 'a_87_sm'] ['f0', 'f1', 'f2', 'f3', 'f4', 'f5', 'f6', 'f7', 'f8', 'f9', 'f10', 'f11', 'f12', 'f13', 'f14', 'f15', 'f16', 'f17', 'f18', 'f19', 'f20', 'f21', 'f22', 'f23', 'f24', 'f25', 'f26', 'f27', 'f28', 'f29', 'f30', 'f31', 'f32', 'f33', 'f34', 'f35', 'f36', 'f37', 'f38', 'f39', 'f40', 'f41', 'f42', 'f43', 'f44', 'f45', 'f46', 'f47', 'f48', 'f49', 'f50', 'f51', 'f52', 'f53', 'f54', 'f55', 'f56', 'f57', 'f58', 'f59', 'f60', 'f61', 'f62', 'f63', 'f64', 'f65', 'f66', 'f67', 'f68']
expected a_33, a_5, a_87_dy, a_8, a_86_id, a_59, a_86_ie, a_63, a_10, a_50, a_12, a_17, a_79, a_84, a_72, a_23, a_21, a_42, a_34, a_27, a_66, a_3, a_22, a_38, a_86_or, a_86_mc, a_20, a_78, a_81, a_9, a_57, a_44, a_6, a_86_tt, a_29, a_40, a_67, a_74, a_11, a_2, a_58, a_30, a_87_or, a_14, a_7, a_13, a_15, a_1, a_36, a_25, a_70, a_28, a_39, a_86_ws, a_73, a_87_el, a_41, a_4, a_85, a_82, a_87_oc, a_68, a_51, a_47, a_0, a_16, a_46, a_87_sm, a_80 in input data
training data did not have the following fields: f7, f27, f31, f1, f20, f61, f25, f43, f66, f2, f4, f16, f44, f46, f64, f14, f18, f15, f52, f57, f19, f38, f40, f11, f12, f37, f65, f45, f56, f10, f67, f33, f36, f3, f0, f6, f41, f47, f39, f49, f50, f53, f8, f60, f58, f62, f30, f17, f51, f48, f24, f59, f32, f26, f5, f22, f42, f28, f9, f35, f34, f23, f63, f29, f54, f68, f21, f13, f55

Training accuracy : 0.999943551300578
Testing accuracy : 0.99603
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     99683
           1       0.16      0.06      0.08       317

    accuracy                           1.00    100000
   macro avg       0.58      0.53      0.54    100000
weighted avg       0.99      1.00      1.00    100000

[[99585    98]
 [  299    18]]
0.15517241379310345
0.056782334384858045
0.99603
0.08314087759815243


In [69]:
from sklearn.ensemble import AdaBoostClassifier

# creating the model
model = AdaBoostClassifier()

# feeding the training data into the model
model.fit(X_train_upsampled, Y_train_upsampled)

# predicting the test set results
y_pred_s = model.predict(X_non_cor_test_1)

# Calculating the accuracies
print("Training accuracy :", model.score(X_train_upsampled, Y_train_upsampled))
print("Testing accuracy :", model.score(X_non_cor_test_1, Y_non_cor_test_1))

# classification report
print(classification_report(Y_non_cor_test_1, y_pred_s))

# confusion matrix 
print(confusion_matrix(Y_non_cor_test_1, y_pred_s))
print(accuracy_score(Y_non_cor_test_1, y_pred_s))
print(precision_score(Y_non_cor_test_1, y_pred_s))
print(recall_score(Y_non_cor_test_1, y_pred_s))
print(f1_score(Y_non_cor_test_1, y_pred_s))


Training accuracy : 0.8169895532273603
Testing accuracy : 0.82829
              precision    recall  f1-score   support

           0       1.00      0.83      0.91     99683
           1       0.01      0.77      0.03       317

    accuracy                           0.83    100000
   macro avg       0.51      0.80      0.47    100000
weighted avg       1.00      0.83      0.90    100000

[[82584 17099]
 [   72   245]]
0.82829
0.014125922509225092
0.7728706624605678
0.027744748315497423


In [70]:
from sklearn.tree import DecisionTreeClassifier

# creating the model
model_s = DecisionTreeClassifier()

# feeding the training data into the model
model_s.fit(X_train_upsampled, Y_train_upsampled)

# predicting the test set results
y_pred_s = model_s.predict(X_non_cor_test_1)

# Calculating the accuracies
print("Training accuracy :", model_s.score(X_train_upsampled, Y_train_upsampled))
print("Testing accuracy :", model_s.score(X_non_cor_test_1, Y_non_cor_test_1))

# classification report
print(classification_report(Y_non_cor_test_1, y_pred_s))

# confusion matrix 
print(confusion_matrix(Y_non_cor_test_1, y_pred_s))
print(accuracy_score(Y_non_cor_test_1, y_pred_s))
print(precision_score(Y_non_cor_test_1, y_pred_s))
print(recall_score(Y_non_cor_test_1, y_pred_s))
print(f1_score(Y_non_cor_test_1, y_pred_s))


Training accuracy : 0.9999987455844573
Testing accuracy : 0.99319
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     99683
           1       0.01      0.02      0.01       317

    accuracy                           0.99    100000
   macro avg       0.51      0.51      0.51    100000
weighted avg       0.99      0.99      0.99    100000

[[99314   369]
 [  312     5]]
0.99319
0.013368983957219251
0.015772870662460567
0.014471780028943561


In [71]:
from sklearn.ensemble import RandomForestClassifier

# creating the model
model_rf = RandomForestClassifier()

# feeding the training data into the model
model_rf.fit(X_train_upsampled, Y_train_upsampled)

# predicting the test set results
y_pred_s = model_rf.predict(X_non_cor_test_1)

# Calculating the accuracies
print("Training accuracy :", model_rf.score(X_train_upsampled, Y_train_upsampled))
print("Testing accuracy :", model_rf.score(X_non_cor_test_1, Y_non_cor_test_1))

# classification report
print(classification_report(Y_non_cor_test_1, y_pred_s))

# confusion matrix 
print(confusion_matrix(Y_non_cor_test_1, y_pred_s))
print(accuracy_score(Y_non_cor_test_1, y_pred_s))
print(precision_score(Y_non_cor_test_1, y_pred_s))
print(recall_score(Y_non_cor_test_1, y_pred_s))
print(f1_score(Y_non_cor_test_1, y_pred_s))

/Users/keshav.somani/.py_venv/lib/python3.6/site-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


Training accuracy : 0.9999974911689146
Testing accuracy : 0.99686
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     99683
           1       0.71      0.02      0.03       317

    accuracy                           1.00    100000
   macro avg       0.86      0.51      0.51    100000
weighted avg       1.00      1.00      1.00    100000

[[99681     2]
 [  312     5]]
0.99686
0.7142857142857143
0.015772870662460567
0.030864197530864192


In [1]:
from sklearn.svm import SVC

# creating the model
model = SVC(gamma="auto", kernel='rbf')

# feeding the training data into the model
model.fit(X_train_upsampled, Y_train_upsampled)

# predicting the test set results
y_pred_s = model.predict(X_non_cor_test_1)

# Calculating the accuracies
print("Training accuracy :", model.score(X_train_upsampled, Y_train_upsampled))
print("Testing accuracy :", model.score(X_non_cor_test_1, Y_non_cor_test_1))

# classification report
print(classification_report(Y_non_cor_test_1, y_pred_s))

# confusion matrix 
print(confusion_matrix(Y_non_cor_test_1, y_pred_s))

NameError: name 'X_train_upsampled' is not defined